version: '3'
services:
  choicery:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: choicery
    networks:
      - choicery
    ports:
      - '3000:3000'
    environment:
     - HOST=0.0.0.0
    command: npm run start
networks:
  choicery:
    driver: bridge
